done lesson 19
timbynce/rack-time-format pull request #1
Opened 2022-07-29 17:08 UTC by timbynce

2022-07-29 18:57 UTC, BubuntuClu requested changes

2022-07-29 18:57 UTC, BubuntuClu commented on app.rb
> +    [status, headers, ["#{body}\n"]]
используй тут объект `Rack::Response` для формирования ответа

2022-07-29 18:57 UTC, BubuntuClu commented on date_format_service.rb
> +  def valid?
почему это публичный метод? ты его используешь только внутри своего класса

2022-07-29 18:57 UTC, BubuntuClu commented on app.rb
> +    response(format_date.resp_status, format_date.resp_body)
```
if format_date.valid?
   response(200,..)
else
  response(400,...)
end
```

2022-07-29 18:57 UTC, BubuntuClu commented on date_format_service.rb
> +  def make_response
я бы вот эту логику вынес в класс выше. чтобы сам `app` управлял логикой тог очто надо сделать, когда запрос успешный или нет.
да и этот класс ничего не должен знать ни о каких статусах. он только парсит параметры и отдает строку времени/ошибки

2022-08-01 06:39 UTC, VidgarVii requested changes

2022-08-01 06:39 UTC, VidgarVii commented on app.rb
> +    return response(404, 'Page not found') unless time_req?
проверку path можно делегировать на утилиту Rack::URLMap. Он как раз будет возвращать 404, если путь не верен

```ruby
require_relative 'time_app'
ROUTES = {
  '/time' => TimeApp.new
}


run Rack::URLMap.new(ROUTES)

2022-08-01 06:39 UTC, VidgarVii commented on app.rb
> +
лишний отступ

2022-08-01 06:39 UTC, VidgarVii commented on app.rb
> +    { "Context-Type" => "text-plain" }
1 Content-Type, а не Context
2 Для настройки ContentType по умолчанию можно воспользоваться настройкой через Rack::ContentType

https://www.rubydoc.info/gems/rack/Rack/ContentType

и этот код будет не нужным

2022-08-01 06:39 UTC, VidgarVii commented on app.rb
> +
лишний отступ

2022-08-01 06:46 UTC, VidgarVii requested changes

2022-08-01 06:46 UTC, VidgarVii commented on middleware/bad_encoding_handler.rb
> +  end
внутри метода сразу писать begin не обязательно
https://github.com/rubocop/ruby-style-guide#begin-implicit

2022-08-30 05:39 UTC, merged